### PR TITLE
test: Add global model tests

### PR DESCRIPTION
**Pull request by francoisWeber**
I added a test file dedicated to global model monitoring (and not the complete categorization mechanism involving the local model) : `services-fixtures-global.spec.js`
Also refactored some displaying functions from `services-fixtures.spec.js`.
Also made some corrections in order to make the whole tests-sets work with the new location of the categorization lib (cozy-konnectors).

### CODE REVIEW

**Comment by nono** [comment]
@francoisWeber can you update this PR to fix the git conflict?

**Comment by nono** [comment]
Ping @francoisWeber

**Comment by francoisWeber** [comment]
Sorry for the delay, @nono : we decided to move this test inside Konnector libs. Actually this PR can be closed. An similar but updated one for Konnector-libs will pop soon.

**Comment by francoisWeber** [comment]
Closed because the target code changed from Banks to Konnector. New similar PR to come soon in the Konnector repo.

**Pull request closed without merging**
