### PR TITLE
feat: Add Planete OUI to brand dictionnary

### PR DESCRIPTION
**Pull request by LucsT**
Add a brand for a brand new connector ^^
Planète Oui

Connector is already available, merge it please.

Thank's

### CODE REVIEW

**Comment by kosssi** [comment]
Can you update test ;)

**Comment by nono** [comment]
Ping @LucsT

**Comment by LucsT** [comment]
@nono @kosssi I updated the test snapshot.

Seems ok to me. But it's first time I do it.  
Done via 'yarn test -u'

**Comment by drazik** [comment]
Thanks!

**Pull request merged**
