### PR TITLE
Validation of bundle produced by webpack

### PR DESCRIPTION
**Pull request by ptbrowne**
Travis will warn us if our build has forbidden syntax.

### CODE REVIEW

**Comment by ptbrowne** [comment]
The script detected errors in our build, I think our bundle has errors on safari ios 10.

```
Validating build/app.js with scripts/bundle-rules.json
- Found ForStatement[init.kind="let"]
  For statements with initializer of kind let does not work in Safari iOS 10
  80:80: for(let r=1;r<t;r++)n+=" "+e[r];
- Found ForStatement[init.kind="let"]
  For statements with initializer of kind let does not work in Safari iOS 10
  80:80: for(let e=1;e<t.length;e++)r.push(String(n[e-1]).replace(/[{}\\]/g,"\\$&")),r.push(String(t.raw[e]));
Error: build/app.js has validation errors
The command "yarn build && node scripts/validate-js.js scripts/bundle-rules.json build/app.js" exited with 1.
```

**Comment by nono** [comment]
Ping @ptbrowne

**Comment by nono** [comment]
Ping @ptbrowne

**Comment by nono** [comment]
ping @ptbrowne

**Pull request closed without merging**
