### PR TITLE
perf: Smaller build 1

### PR DESCRIPTION
**Pull request by ptbrowne**
Bigger issue : https://github.com/cozy/cozy-banks/issues/926

Baseline: 2421ko

image

- Remove duplicate lib via webpack aliasing : 2317ko

image

- Do not bundle all d3 inside build : 2179ko

image

### CODE REVIEW

**Comment by nono** [comment]
Some other ideas:

- remove the Fetch polyfill (it is no longer needed for the browsers we support)
- use lazy loading for the graphs libs
- redux-raven-middleware and raven.js seems to load the same files: are both necessary?
- try svgo on icon-collect-account.svg

**Comment by nono** [comment]
> Cozy Authentication build ? Why is it so big ?

It embeds 65ko of CSS from cozy-ui, and some stylus things

**Comment by kosssi** [comment]
I don’t see the interest in minifying image, it should be webpack that handles this, no ?

**Comment by nono** [comment]
Well, there are some pros and cons to do that. For example, minifying images can take a lot of time and make the build really slower.

**Comment by ptbrowne** [comment]
> I don’t see the interest in minifying image, it should be webpack that handles this, no ?

Since

**Pull request merged**
