### PR TITLE
[VO-598] fix: Make closable the HarvestModal in banks settings

### PR DESCRIPTION
**Pull request by cballevre**
```
### 🐛 Bug Fixes

* Make closable the HarvestModal in banks settings
```

### CODE REVIEW

**Comment by Merkur39** [comment]
Travis n'est pas lancé ? 🤔

**Comment by cballevre** [comment]
> Travis n'est pas lancé ? 🤔

I don't know why, but that's a good point

**Comment by cballevre** [comment]
@Merkur39 I relaunch it with push but I don't know it didn't start in the first place. I'd take this opportunity to ask you for a review? pls 🙏

**Review by Merkur39 — APPROVED** [review]
Look's good 👍

**Pull request merged**
